framework:
    rate_limiter:
        tracking_open:
            policy: sliding_window
            limit: 200
            interval: '1 minute'
            cache_pool: cache.app
        tracking_click:
            policy: sliding_window
            limit: 100
            interval: '1 minute'
            cache_pool: cache.app
        unsubscribe:
            policy: sliding_window
            limit: 30
            interval: '1 minute'
            cache_pool: cache.app
        subscribe:
            policy: sliding_window
            limit: 10
            interval: '1 minute'
            cache_pool: cache.app
