<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SEQUENCE account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE campaign_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE campaign_email_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE link_stat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE open_stat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_account_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE account (id INT NOT NULL, ragione_sociale VARCHAR(255) NOT NULL, email_contatto VARCHAR(255) NOT NULL, partita_iva VARCHAR(30) DEFAULT NULL, indirizzo TEXT DEFAULT NULL, mailer_dsn TEXT DEFAULT NULL, smtp_host VARCHAR(255) DEFAULT NULL, smtp_port INT DEFAULT NULL, smtp_user VARCHAR(255) DEFAULT NULL, smtp_password VARCHAR(255) DEFAULT NULL, smtp_encryption VARCHAR(20) DEFAULT NULL, batch_size INT DEFAULT 50 NOT NULL, send_interval INT DEFAULT 30 NOT NULL, api_key VARCHAR(64) NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, logo_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7D3656A4C912ED9D ON account (api_key)');
        $this->addSql('CREATE INDEX IDX_7D3656A4F98F144A ON account (logo_id)');
        $this->addSql('CREATE TABLE campaign (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, email_subject VARCHAR(255) NOT NULL, snippet VARCHAR(255) DEFAULT NULL, body TEXT DEFAULT NULL, structure JSON DEFAULT NULL, composition JSON DEFAULT NULL, filter JSON DEFAULT NULL, draft BOOLEAN DEFAULT false NOT NULL, template BOOLEAN DEFAULT false NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1512DD9B6B5FBA ON campaign (account_id)');
        $this->addSql('CREATE TABLE campaign_mail_list (campaign_id INT NOT NULL, mail_list_id INT NOT NULL, PRIMARY KEY (campaign_id, mail_list_id))');
        $this->addSql('CREATE INDEX IDX_293B770AF639F774 ON campaign_mail_list (campaign_id)');
        $this->addSql('CREATE INDEX IDX_293B770AE71397E4 ON campaign_mail_list (mail_list_id)');
        $this->addSql('CREATE TABLE campaign_email (id INT NOT NULL, email VARCHAR(255) NOT NULL, tracking_open_id VARCHAR(36) NOT NULL, status VARCHAR(20) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, retry_count INT DEFAULT 0 NOT NULL, campaign_id INT NOT NULL, contact_id INT DEFAULT NULL, mail_list_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A997181B87590BA4 ON campaign_email (tracking_open_id)');
        $this->addSql('CREATE INDEX IDX_A997181BF639F774 ON campaign_email (campaign_id)');
        $this->addSql('CREATE INDEX IDX_A997181BE7A1254A ON campaign_email (contact_id)');
        $this->addSql('CREATE INDEX IDX_A997181BE71397E4 ON campaign_email (mail_list_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, nome VARCHAR(100) DEFAULT NULL, cognome VARCHAR(100) DEFAULT NULL, telefono VARCHAR(30) DEFAULT NULL, iscritto BOOLEAN DEFAULT true NOT NULL, bounce_count INT DEFAULT 0 NOT NULL, mail_list_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E638E71397E4 ON contact (mail_list_id)');
        $this->addSql('CREATE TABLE contact_taxonomy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contact_id INT NOT NULL, term_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_673724AAE7A1254A ON contact_taxonomy (contact_id)');
        $this->addSql('CREATE INDEX IDX_673724AAE2C35FC ON contact_taxonomy (term_id)');
        $this->addSql('CREATE UNIQUE INDEX contact_term_unique ON contact_taxonomy (contact_id, term_id)');
        $this->addSql('CREATE TABLE geo_alternatenames (alternatenameid BIGINT NOT NULL, isolanguage VARCHAR(7) DEFAULT NULL, alternate_name VARCHAR(400) NOT NULL, preferred_name BOOLEAN NOT NULL, short_name BOOLEAN NOT NULL, colloquial BOOLEAN NOT NULL, historic BOOLEAN NOT NULL, from_date VARCHAR(10) DEFAULT NULL, to_date VARCHAR(10) DEFAULT NULL, geonameid_id BIGINT DEFAULT NULL, PRIMARY KEY (alternatenameid))');
        $this->addSql('CREATE INDEX IDX_6088DD8A5AE06FA ON geo_alternatenames (geonameid_id)');
        $this->addSql('CREATE INDEX geo_alternate_isolanguage ON geo_alternatenames (isolanguage)');
        $this->addSql('CREATE TABLE geo_alternatenames_tmp (alternatenameid BIGINT NOT NULL, geonameid BIGINT NOT NULL, isolanguage VARCHAR(7) DEFAULT NULL, alternate_name VARCHAR(400) NOT NULL, preferred_name BOOLEAN DEFAULT NULL, short_name BOOLEAN DEFAULT NULL, colloquial BOOLEAN DEFAULT NULL, historic BOOLEAN DEFAULT NULL, from_date VARCHAR(10) DEFAULT NULL, to_date VARCHAR(10) DEFAULT NULL, PRIMARY KEY (alternatenameid))');
        $this->addSql('CREATE TABLE geo_countries (iso VARCHAR(2) NOT NULL, iso3 VARCHAR(3) NOT NULL, iso_numeric VARCHAR(3) NOT NULL, fips VARCHAR(2) DEFAULT NULL, country VARCHAR(64) NOT NULL, capital VARCHAR(64) DEFAULT NULL, area NUMERIC(10, 1) DEFAULT NULL, population INT NOT NULL, continent VARCHAR(2) NOT NULL, tld VARCHAR(5) DEFAULT NULL, currency_code VARCHAR(3) DEFAULT NULL, currency_name VARCHAR(16) DEFAULT NULL, phone VARCHAR(32) DEFAULT NULL, postal_code_format VARCHAR(255) DEFAULT NULL, postal_code_regex VARCHAR(255) DEFAULT NULL, languages VARCHAR(255) DEFAULT NULL, geonameid INT DEFAULT NULL, neighbours VARCHAR(255) DEFAULT NULL, equivalent_fips_code VARCHAR(2) DEFAULT NULL, PRIMARY KEY (iso))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC59C1A46C68A7E2 ON geo_countries (iso3)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC59C1A48871CBE0 ON geo_countries (iso_numeric)');
        $this->addSql('CREATE TABLE geo_names (geonameid BIGINT NOT NULL, name VARCHAR(200) NOT NULL, asciiname VARCHAR(200) NOT NULL, alternatenames TEXT DEFAULT NULL, latitude NUMERIC(15, 10) DEFAULT NULL, longitude NUMERIC(15, 10) DEFAULT NULL, feature_class VARCHAR(1) DEFAULT NULL, feature_code VARCHAR(10) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, ccs VARCHAR(255) DEFAULT NULL, admin1_code VARCHAR(20) DEFAULT NULL, admin2_code VARCHAR(80) DEFAULT NULL, admin3_code VARCHAR(20) DEFAULT NULL, admin4_code VARCHAR(20) DEFAULT NULL, elevation BIGINT DEFAULT NULL, dem BIGINT DEFAULT NULL, population BIGINT DEFAULT NULL, timezone VARCHAR(32) DEFAULT NULL, modification_date DATE DEFAULT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY (geonameid))');
        $this->addSql('CREATE INDEX geo_country_code ON geo_names (country_code)');
        $this->addSql('CREATE INDEX geo_feature_code ON geo_names (feature_code)');
        $this->addSql('CREATE INDEX geo_lat ON geo_names (latitude)');
        $this->addSql('CREATE INDEX geo_lon ON geo_names (longitude)');
        $this->addSql('CREATE INDEX geo_pop ON geo_names (population)');
        $this->addSql('CREATE TABLE geo_names_tmp (geonameid BIGINT NOT NULL, name VARCHAR(200) NOT NULL, asciiname VARCHAR(200) NOT NULL, alternatenames TEXT DEFAULT NULL, latitude NUMERIC(15, 10) DEFAULT NULL, longitude NUMERIC(15, 10) DEFAULT NULL, feature_class VARCHAR(1) DEFAULT NULL, feature_code VARCHAR(10) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, ccs VARCHAR(255) DEFAULT NULL, admin1_code VARCHAR(20) DEFAULT NULL, admin2_code VARCHAR(80) DEFAULT NULL, admin3_code VARCHAR(20) DEFAULT NULL, admin4_code VARCHAR(20) DEFAULT NULL, elevation BIGINT DEFAULT NULL, dem BIGINT DEFAULT NULL, population BIGINT DEFAULT NULL, timezone VARCHAR(32) DEFAULT NULL, modification_date DATE DEFAULT NULL, PRIMARY KEY (geonameid))');
        $this->addSql('CREATE TABLE geo_postal_code (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country_code VARCHAR(2) NOT NULL, postal_code VARCHAR(20) NOT NULL, place_name VARCHAR(180) DEFAULT NULL, admin_name1 VARCHAR(100) DEFAULT NULL, admin_code1 VARCHAR(20) DEFAULT NULL, admin_name2 VARCHAR(100) DEFAULT NULL, admin_code2 VARCHAR(20) DEFAULT NULL, admin_name3 VARCHAR(100) DEFAULT NULL, admin_code3 VARCHAR(20) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, accuracy SMALLINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE link_stat (id INT NOT NULL, url TEXT NOT NULL, tracking_token VARCHAR(36) NOT NULL, clicked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, first_clicked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, count INT DEFAULT 1 NOT NULL, campaign_email_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_91FF6D88B46BB896 ON link_stat (tracking_token)');
        $this->addSql('CREATE INDEX IDX_91FF6D889A4217B6 ON link_stat (campaign_email_id)');
        $this->addSql('CREATE TABLE mail_list (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, firma_html TEXT DEFAULT NULL, mailer_dsn_override VARCHAR(500) DEFAULT NULL, permetti_disiscrizione BOOLEAN DEFAULT true NOT NULL, account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E9B36B719B6B5FBA ON mail_list (account_id)');
        $this->addSql('CREATE TABLE mailer_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, address_from VARCHAR(255) NOT NULL, address_from_name VARCHAR(255) DEFAULT NULL, address_to VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, html TEXT NOT NULL, txt TEXT NOT NULL, batch INT NOT NULL, send_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, response TEXT NOT NULL, family VARCHAR(255) DEFAULT NULL, attachments JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE oi_user_api_refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F0C6E007C74F2195 ON oi_user_api_refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE open_stat (id INT NOT NULL, opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, first_opened_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, count INT DEFAULT 1 NOT NULL, campaign_email_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_994CBE049A4217B6 ON open_stat (campaign_email_id)');
        $this->addSql('CREATE TABLE sequence_service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, number INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D597530A5E237E06 ON sequence_service (name)');
        $this->addSql('CREATE TABLE smart_app_banner (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(255) DEFAULT NULL, operation VARCHAR(8) NOT NULL, os VARCHAR(8) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE taxonomy_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, mail_list_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ABAC3116E71397E4 ON taxonomy_category (mail_list_id)');
        $this->addSql('CREATE TABLE taxonomy_term (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C7ED653A12469DE2 ON taxonomy_term (category_id)');
        $this->addSql('CREATE TABLE unsubscribe_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, campaign_email_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_35C706459A4217B6 ON unsubscribe_request (campaign_email_id)');
        $this->addSql('CREATE TABLE upload (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) DEFAULT NULL, alt_image JSON DEFAULT NULL, title JSON DEFAULT NULL, caption JSON DEFAULT NULL, description JSON DEFAULT NULL, sort_order SMALLINT DEFAULT NULL, size INT NOT NULL, mimetype VARCHAR(255) NOT NULL, area VARCHAR(255) DEFAULT NULL, dir VARCHAR(255) DEFAULT NULL, json JSON DEFAULT NULL, created_by VARCHAR(255) DEFAULT NULL, updated_by VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_account (id INT NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, confirmation_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmed BOOLEAN DEFAULT false NOT NULL, password_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, disabled BOOLEAN DEFAULT false NOT NULL, first_login_token VARCHAR(255) DEFAULT NULL, first_login_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email VARCHAR(180) NOT NULL, new_email VARCHAR(180) DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, account_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_253B48AEC05FB297 ON user_account (confirmation_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_253B48AEBEAB6C24 ON user_account (password_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_253B48AEC7B26B6D ON user_account (first_login_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_253B48AEE7927C74 ON user_account (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_253B48AE9B6B5FBA ON user_account (account_id)');
        $this->addSql('CREATE TABLE version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, os VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, build INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4F98F144A FOREIGN KEY (logo_id) REFERENCES upload (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_mail_list ADD CONSTRAINT FK_293B770AF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE campaign_mail_list ADD CONSTRAINT FK_293B770AE71397E4 FOREIGN KEY (mail_list_id) REFERENCES mail_list (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE campaign_email ADD CONSTRAINT FK_A997181BF639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_email ADD CONSTRAINT FK_A997181BE7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign_email ADD CONSTRAINT FK_A997181BE71397E4 FOREIGN KEY (mail_list_id) REFERENCES mail_list (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638E71397E4 FOREIGN KEY (mail_list_id) REFERENCES mail_list (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact_taxonomy ADD CONSTRAINT FK_673724AAE7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact_taxonomy ADD CONSTRAINT FK_673724AAE2C35FC FOREIGN KEY (term_id) REFERENCES taxonomy_term (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE geo_alternatenames ADD CONSTRAINT FK_6088DD8A5AE06FA FOREIGN KEY (geonameid_id) REFERENCES geo_names (geonameid) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE link_stat ADD CONSTRAINT FK_91FF6D889A4217B6 FOREIGN KEY (campaign_email_id) REFERENCES campaign_email (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mail_list ADD CONSTRAINT FK_E9B36B719B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE open_stat ADD CONSTRAINT FK_994CBE049A4217B6 FOREIGN KEY (campaign_email_id) REFERENCES campaign_email (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_category ADD CONSTRAINT FK_ABAC3116E71397E4 FOREIGN KEY (mail_list_id) REFERENCES mail_list (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE taxonomy_term ADD CONSTRAINT FK_C7ED653A12469DE2 FOREIGN KEY (category_id) REFERENCES taxonomy_category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unsubscribe_request ADD CONSTRAINT FK_35C706459A4217B6 FOREIGN KEY (campaign_email_id) REFERENCES campaign_email (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_account ADD CONSTRAINT FK_253B48AE9B6B5FBA FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP SEQUENCE account_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE campaign_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE campaign_email_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE link_stat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE open_stat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_account_id_seq CASCADE');
        $this->addSql('ALTER TABLE account DROP CONSTRAINT FK_7D3656A4F98F144A');
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_1F1512DD9B6B5FBA');
        $this->addSql('ALTER TABLE campaign_mail_list DROP CONSTRAINT FK_293B770AF639F774');
        $this->addSql('ALTER TABLE campaign_mail_list DROP CONSTRAINT FK_293B770AE71397E4');
        $this->addSql('ALTER TABLE campaign_email DROP CONSTRAINT FK_A997181BF639F774');
        $this->addSql('ALTER TABLE campaign_email DROP CONSTRAINT FK_A997181BE7A1254A');
        $this->addSql('ALTER TABLE campaign_email DROP CONSTRAINT FK_A997181BE71397E4');
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E638E71397E4');
        $this->addSql('ALTER TABLE contact_taxonomy DROP CONSTRAINT FK_673724AAE7A1254A');
        $this->addSql('ALTER TABLE contact_taxonomy DROP CONSTRAINT FK_673724AAE2C35FC');
        $this->addSql('ALTER TABLE geo_alternatenames DROP CONSTRAINT FK_6088DD8A5AE06FA');
        $this->addSql('ALTER TABLE link_stat DROP CONSTRAINT FK_91FF6D889A4217B6');
        $this->addSql('ALTER TABLE mail_list DROP CONSTRAINT FK_E9B36B719B6B5FBA');
        $this->addSql('ALTER TABLE open_stat DROP CONSTRAINT FK_994CBE049A4217B6');
        $this->addSql('ALTER TABLE taxonomy_category DROP CONSTRAINT FK_ABAC3116E71397E4');
        $this->addSql('ALTER TABLE taxonomy_term DROP CONSTRAINT FK_C7ED653A12469DE2');
        $this->addSql('ALTER TABLE unsubscribe_request DROP CONSTRAINT FK_35C706459A4217B6');
        $this->addSql('ALTER TABLE user_account DROP CONSTRAINT FK_253B48AE9B6B5FBA');
        $this->addSql('DROP TABLE account');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('DROP TABLE campaign_mail_list');
        $this->addSql('DROP TABLE campaign_email');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE contact_taxonomy');
        $this->addSql('DROP TABLE geo_alternatenames');
        $this->addSql('DROP TABLE geo_alternatenames_tmp');
        $this->addSql('DROP TABLE geo_countries');
        $this->addSql('DROP TABLE geo_names');
        $this->addSql('DROP TABLE geo_names_tmp');
        $this->addSql('DROP TABLE geo_postal_code');
        $this->addSql('DROP TABLE link_stat');
        $this->addSql('DROP TABLE mail_list');
        $this->addSql('DROP TABLE mailer_log');
        $this->addSql('DROP TABLE oi_user_api_refresh_tokens');
        $this->addSql('DROP TABLE open_stat');
        $this->addSql('DROP TABLE sequence_service');
        $this->addSql('DROP TABLE smart_app_banner');
        $this->addSql('DROP TABLE taxonomy_category');
        $this->addSql('DROP TABLE taxonomy_term');
        $this->addSql('DROP TABLE unsubscribe_request');
        $this->addSql('DROP TABLE upload');
        $this->addSql('DROP TABLE user_account');
        $this->addSql('DROP TABLE version');
    }
}
