<?php

namespace App\Tests\Service;

use App\Entity\Account;
use App\Service\PublicApiRateLimiter;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Cache\Adapter\ArrayAdapter;

class PublicApiRateLimiterTest extends TestCase
{
    public function testConsumeRespectsPerAccountLimit(): void
    {
        $cache = new ArrayAdapter();
        $rateLimiter = new PublicApiRateLimiter($cache);

        $account = new Account();
        // Set id via reflection since it's auto-generated by Doctrine
        $ref = new \ReflectionProperty(Account::class, 'id');
        $ref->setValue($account, 42);
        $account->setApiRateLimit(60);

        for ($i = 1; $i <= 60; $i++) {
            $result = $rateLimiter->consume($account);
            $this->assertTrue($result->isAccepted(), "Call $i should be accepted");
        }

        for ($i = 61; $i <= 70; $i++) {
            $result = $rateLimiter->consume($account);
            $this->assertFalse($result->isAccepted(), "Call $i should be rejected");
        }
    }
}
