controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# backend:
#     resource: ../src/Controller/Backend/*
#     type: attribute
#     prefix: /api
#     options:
#         api_versions:
#             - !php/const Oi\ApiBundle\Helper\ApiVersion::V1
# frontend:
#     resource: ../src/Controller/Frontend/*
#     type: attribute
#     prefix: /api
#     options:
#         api_versions:
#             - !php/const Oi\ApiBundle\Helper\ApiVersion::V1

api_uploader_upload_files:
    path: /api/_uploader/files/upload
    controller: oneup_uploader.controller.files::upload
    methods: [ 'POST', 'PUT', 'PATCH' ]
    options:
        api_versions:
            - !php/const Oi\ApiBundle\Helper\ApiVersion::V1
    defaults:
        _format: json

api_delete_files:
    path: /api/files/delete/{id}
    controller: Oi\FileBundle\Controller\DefaultController::deleteAction
    methods: [ 'DELETE' ]
    options:
        api_versions:
            - !php/const Oi\ApiBundle\Helper\ApiVersion::V1
